version: "3.8"

services:

  edge_a:
    privileged: true
    build:
      context: ./wan
      dockerfile: edge_a.dockerfile
    ports:
      - "60001:22"
    tty: true
    networks:
      default:
        ipv4_address: 172.24.0.101
      remote_site:
        ipv4_address: 10.1.1.101
    hostname: EDGE_A

  edge_b:
    privileged: true
    build:
      context: ./wan
      dockerfile: edge_b.dockerfile
    ports:
      - "60002:22"
    tty: true
    networks:
      default:
        ipv4_address: 172.24.0.102
      local_site_b:
        ipv4_address: 10.1.2.101
    hostname: EDGE_B

  edge_c:
    privileged: true
    build:
      context: ./wan
      dockerfile: edge_c.dockerfile
    ports:
      - "60003:22"
    tty: true
    networks:
      default:
        ipv4_address: 172.24.0.103
      local_site_c:
        ipv4_address: 10.1.3.101
    hostname: EDGE_C

  routeros:
    privileged: true
    build:
      context: ./routeros
      dockerfile: routeros.dockerfile
    ports:
      - "60004:22"
    tty: true
    networks:
      remote_site:
        ipv4_address: 10.1.1.110
    hostname: routeros

  router_a:
    privileged: true
    build:
      context: ./lan
      dockerfile: router_a.dockerfile
    ports:
      - "60005:22"
    tty: true
    networks:
      remote_site:
        ipv4_address: 10.1.1.102
    hostname: router_a

  router_b:
    privileged: true
    build:
      context: ./lan
      dockerfile: router_b.dockerfile
    ports:
      - "60006:22"
    tty: true
    networks:
      local_site_b:
        ipv4_address: 10.1.2.102
    hostname: router_b

  router_c:
    privileged: true
    build:
      context: ./lan
      dockerfile: router_c.dockerfile
    ports:
      - "60007:22"
    tty: true
    networks:
      local_site_c:
        ipv4_address: 10.1.3.102
    hostname: router_c

networks:
  default:
    ipam:
      config:
        - subnet: 172.24.0.0/24
  remote_site:
    ipam:
      config:
        - subnet: 10.1.1.0/24
  local_site_b:
    ipam:
      config:
        - subnet: 10.1.2.0/24
  local_site_c:
    ipam:
      config:
        - subnet: 10.1.3.0/24
